org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# Enable R8 full mode for maximum optimizations and dead code removal
android.enableR8.fullMode=true

# Enable integrated AGP/R8 optimized resource shrinking
android.r8.optimizedResourceShrinking=true
